import '../val_highlight.dart';

/// The default dark theme.
const darkTheme = ValTheme(
  name: 'dark',
  dark: true,
  root: Style(color: 0xFFD6DAE0, background: 0xFF16181D),
  styles: {
    Scopes.comment: Style(color: 0xFF7F8792, italic: true),
    Scopes.commentDoc: Style(color: 0xFF7E9A88, italic: true),
    Scopes.string: Style(color: 0xFF8BD49C),
    Scopes.stringEscape: Style(color: 0xFF6BD9E3),
    Scopes.interpolation: Style(color: 0xFFD6DAE0),
    Scopes.number: Style(color: 0xFFF0B46A),
    Scopes.keyword: Style(color: 0xFFFF7AB6),
    Scopes.literal: Style(color: 0xFF79B8FF),
    Scopes.type: Style(color: 0xFFC4A5FF),
    Scopes.typeBuiltin: Style(color: 0xFF79B8FF),
    Scopes.function: Style(color: 0xFFFFD580),
    Scopes.variable: Style(color: 0xFFE0A5FF),
    Scopes.variableLanguage: Style(color: 0xFFFF7AB6, italic: true),
    Scopes.meta: Style(color: 0xFFB392F0),
    Scopes.property: Style(color: 0xFF79B8FF),
    Scopes.punctuation: Style(color: 0xFF9BA3AE),
    Scopes.operator: Style(color: 0xFF9BA3AE),
    Scopes.tag: Style(color: 0xFFFF7AB6),
    Scopes.attribute: Style(color: 0xFFC4A5FF),
    Scopes.regexp: Style(color: 0xFF6BD9E3),
    Scopes.heading: Style(color: 0xFF79B8FF, bold: true),
    Scopes.emphasis: Style(italic: true),
    Scopes.strong: Style(bold: true),
    Scopes.link: Style(color: 0xFF79B8FF, underline: true),
    Scopes.code: Style(color: 0xFF8BD49C),
    Scopes.quote: Style(color: 0xFF7F8792, italic: true),
    Scopes.addition: Style(color: 0xFF8BD49C, background: 0xFF1B3325),
    Scopes.deletion: Style(color: 0xFFFF9492, background: 0xFF3D1F20),
    Scopes.invalid: Style(color: 0xFFFF9492, underline: true),
  },
);
