import '../val_highlight.dart';

/// A soft, low-glare dark theme.
const dimTheme = ValTheme(
  name: 'dim',
  dark: true,
  root: Style(color: 0xFFC4C8CE, background: 0xFF22262C),
  styles: {
    Scopes.comment: Style(color: 0xFF8E949C, italic: true),
    Scopes.commentDoc: Style(color: 0xFF8FA096, italic: true),
    Scopes.string: Style(color: 0xFFA9C79A),
    Scopes.stringEscape: Style(color: 0xFF8CC4C4),
    Scopes.interpolation: Style(color: 0xFFC4C8CE),
    Scopes.number: Style(color: 0xFFD4B08A),
    Scopes.keyword: Style(color: 0xFFD49AB6),
    Scopes.literal: Style(color: 0xFF96B4D8),
    Scopes.type: Style(color: 0xFFB8A6D6),
    Scopes.typeBuiltin: Style(color: 0xFF96B4D8),
    Scopes.function: Style(color: 0xFFD8C495),
    Scopes.variable: Style(color: 0xFFC8A8D8),
    Scopes.variableLanguage: Style(color: 0xFFD49AB6, italic: true),
    Scopes.meta: Style(color: 0xFFAEA0D0),
    Scopes.property: Style(color: 0xFF96B4D8),
    Scopes.punctuation: Style(color: 0xFFA3A8AF),
    Scopes.operator: Style(color: 0xFFA3A8AF),
    Scopes.tag: Style(color: 0xFFD49AB6),
    Scopes.attribute: Style(color: 0xFFB8A6D6),
    Scopes.regexp: Style(color: 0xFF8CC4C4),
    Scopes.heading: Style(color: 0xFF96B4D8, bold: true),
    Scopes.emphasis: Style(italic: true),
    Scopes.strong: Style(bold: true),
    Scopes.link: Style(color: 0xFF96B4D8, underline: true),
    Scopes.code: Style(color: 0xFFA9C79A),
    Scopes.quote: Style(color: 0xFF8E949C, italic: true),
    Scopes.addition: Style(color: 0xFFA9C79A, background: 0xFF2C3A2C),
    Scopes.deletion: Style(color: 0xFFE0A0A0, background: 0xFF3E2A2C),
    Scopes.invalid: Style(color: 0xFFE0A0A0, underline: true),
  },
);
