import '../val_highlight.dart';

/// A green-tinted dark theme.
const forestTheme = ValTheme(
  name: 'forest',
  dark: true,
  root: Style(color: 0xFFD6E2D0, background: 0xFF15201A),
  styles: {
    Scopes.comment: Style(color: 0xFF7F9486, italic: true),
    Scopes.commentDoc: Style(color: 0xFF8FA48A, italic: true),
    Scopes.string: Style(color: 0xFFB5D98A),
    Scopes.stringEscape: Style(color: 0xFF84D2BE),
    Scopes.interpolation: Style(color: 0xFFD6E2D0),
    Scopes.number: Style(color: 0xFFE8B87A),
    Scopes.keyword: Style(color: 0xFF86CFA4),
    Scopes.literal: Style(color: 0xFFE89A7A),
    Scopes.type: Style(color: 0xFFC6D67A),
    Scopes.typeBuiltin: Style(color: 0xFF86CFA4),
    Scopes.function: Style(color: 0xFFE6CF86),
    Scopes.variable: Style(color: 0xFFB8C8E8),
    Scopes.variableLanguage: Style(color: 0xFF86CFA4, italic: true),
    Scopes.meta: Style(color: 0xFFA8BFA0),
    Scopes.property: Style(color: 0xFF9CC8D8),
    Scopes.punctuation: Style(color: 0xFF9CAE9E),
    Scopes.operator: Style(color: 0xFF9CAE9E),
    Scopes.tag: Style(color: 0xFF86CFA4),
    Scopes.attribute: Style(color: 0xFFC6D67A),
    Scopes.regexp: Style(color: 0xFF84D2BE),
    Scopes.heading: Style(color: 0xFFB5D98A, bold: true),
    Scopes.emphasis: Style(italic: true),
    Scopes.strong: Style(bold: true),
    Scopes.link: Style(color: 0xFFE89A7A, underline: true),
    Scopes.code: Style(color: 0xFFB5D98A),
    Scopes.quote: Style(color: 0xFF7F9486, italic: true),
    Scopes.addition: Style(color: 0xFFB5D98A, background: 0xFF20381F),
    Scopes.deletion: Style(color: 0xFFF0A08A, background: 0xFF3A2220),
    Scopes.invalid: Style(color: 0xFFF0A08A, underline: true),
  },
);
