import '../val_highlight.dart';

/// A high-contrast dark theme: every colour has at least 7:1 contrast.
const highContrastDarkTheme = ValTheme(
  name: 'high-contrast-dark',
  dark: true,
  root: Style(color: 0xFFFFFFFF, background: 0xFF000000),
  styles: {
    Scopes.comment: Style(color: 0xFFB8B8B8, italic: true),
    Scopes.commentDoc: Style(color: 0xFFB0D0B0, italic: true),
    Scopes.string: Style(color: 0xFFA8F0A0),
    Scopes.stringEscape: Style(color: 0xFF8CF0F0),
    Scopes.interpolation: Style(color: 0xFFFFFFFF),
    Scopes.number: Style(color: 0xFFFFD08A),
    Scopes.keyword: Style(color: 0xFFFFA8D8),
    Scopes.literal: Style(color: 0xFFA8D0FF),
    Scopes.type: Style(color: 0xFFD8C0FF),
    Scopes.typeBuiltin: Style(color: 0xFFA8D0FF),
    Scopes.function: Style(color: 0xFFFFE8A0),
    Scopes.variable: Style(color: 0xFFE0C8FF),
    Scopes.variableLanguage: Style(color: 0xFFFFA8D8, italic: true),
    Scopes.meta: Style(color: 0xFFD0C0FF),
    Scopes.property: Style(color: 0xFFA8D0FF),
    Scopes.punctuation: Style(color: 0xFFD0D0D0),
    Scopes.operator: Style(color: 0xFFD0D0D0),
    Scopes.tag: Style(color: 0xFFFFA8D8),
    Scopes.attribute: Style(color: 0xFFD8C0FF),
    Scopes.regexp: Style(color: 0xFF8CF0F0),
    Scopes.heading: Style(color: 0xFFA8D0FF, bold: true),
    Scopes.emphasis: Style(italic: true),
    Scopes.strong: Style(bold: true),
    Scopes.link: Style(color: 0xFFA8D0FF, underline: true),
    Scopes.code: Style(color: 0xFFA8F0A0),
    Scopes.quote: Style(color: 0xFFB8B8B8, italic: true),
    Scopes.addition: Style(color: 0xFFA8F0A0, background: 0xFF0E2A10),
    Scopes.deletion: Style(color: 0xFFFFB0B0, background: 0xFF2E0E0E),
    Scopes.invalid: Style(color: 0xFFFFB0B0, underline: true),
  },
);
