import '../val_highlight.dart';

/// A deep blue dark theme.
const midnightTheme = ValTheme(
  name: 'midnight',
  dark: true,
  root: Style(color: 0xFFD8E0F0, background: 0xFF0E1628),
  styles: {
    Scopes.comment: Style(color: 0xFF7F8DAA, italic: true),
    Scopes.commentDoc: Style(color: 0xFF84A0A8, italic: true),
    Scopes.string: Style(color: 0xFF8FD7A8),
    Scopes.stringEscape: Style(color: 0xFF7AD4E6),
    Scopes.interpolation: Style(color: 0xFFD8E0F0),
    Scopes.number: Style(color: 0xFFF2B880),
    Scopes.keyword: Style(color: 0xFF9DB4FF),
    Scopes.literal: Style(color: 0xFFF29AB0),
    Scopes.type: Style(color: 0xFF7FD0FF),
    Scopes.typeBuiltin: Style(color: 0xFF9DB4FF),
    Scopes.function: Style(color: 0xFFE8D48A),
    Scopes.variable: Style(color: 0xFFC9A8FF),
    Scopes.variableLanguage: Style(color: 0xFF9DB4FF, italic: true),
    Scopes.meta: Style(color: 0xFFB9A0F0),
    Scopes.property: Style(color: 0xFF86C8F0),
    Scopes.punctuation: Style(color: 0xFF9AA6C0),
    Scopes.operator: Style(color: 0xFF9AA6C0),
    Scopes.tag: Style(color: 0xFF9DB4FF),
    Scopes.attribute: Style(color: 0xFF7FD0FF),
    Scopes.regexp: Style(color: 0xFF7AD4E6),
    Scopes.heading: Style(color: 0xFF9DB4FF, bold: true),
    Scopes.emphasis: Style(italic: true),
    Scopes.strong: Style(bold: true),
    Scopes.link: Style(color: 0xFFF29AB0, underline: true),
    Scopes.code: Style(color: 0xFF8FD7A8),
    Scopes.quote: Style(color: 0xFF7F8DAA, italic: true),
    Scopes.addition: Style(color: 0xFF8FD7A8, background: 0xFF123524),
    Scopes.deletion: Style(color: 0xFFFF9E9E, background: 0xFF3A1A24),
    Scopes.invalid: Style(color: 0xFFFF9E9E, underline: true),
  },
);
