// Generates lib/samples.g.dart from the core package's golden inputs, so the
// gallery shows reviewed, realistic code for every language.
//
//   dart run tool/generate_samples.dart
import 'dart:io';

void main() {
  final inputs =
      Directory(
          '../../val_highlight/test/golden_inputs',
        ).listSync().whereType<File>().toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_samples.dart. Do not edit.')
    ..writeln()
    ..writeln('/// Sample code per language name.')
    ..writeln('const generatedSamples = <String, String>{');
  for (final file in inputs) {
    final name = file.uri.pathSegments.last.split('.').first;
    final text = file
        .readAsStringSync()
        .replaceAll(r'\', r'\\')
        .replaceAll("'", r"\'")
        .replaceAll(r'$', r'\$')
        .replaceAll('\r', r'\r')
        .replaceAll('\n', r'\n');
    out.writeln("  '$name': '$text',");
  }
  out.writeln('};');
  File('lib/samples.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${inputs.length} samples.');
}
